name: Node.js CI

on: [pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm i, run build and run test:unit
      run: |
        cd './src/MTGCore.ClientApp/ClientApp'
        npm i
        npm run build --if-present
        npm run test:unit --if-present
      env:
        CI: true
